name: grocery_onlineapp
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  get: ^4.1.4
  http: ^0.13.1
  flutter_bloc: ^7.0.0
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  internet_connection_checker: ^0.0.1+1
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  image_picker: ^0.7.4
  shimmer_animation: ^2.0.0
  pinput: ^1.2.0
  pin_code_text_field: ^1.8.0
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  toast: ^0.1.5
  flutter_local_notifications: ^5.0.0+1
  firebase_messaging: ^10.0.1
  fluttertoast: ^8.0.7
  intl: ^0.17.0
  pin_input_text_field: ^4.0.0
  flutter_swiper: ^1.1.6
  percent_indicator: ^3.0.1
  flushbar: ^1.10.4
  carousel_slider: ^3.0.0
  scratcher: "^2.1.0"
  flutter_rating_bar: ^4.0.0
  flutter_phoenix: ^1.0.0
  grouped_buttons: ^1.0.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.1
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  flutter_html: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  google_maps_flutter: ^2.0.2
  flutter_google_places: ^0.3.0
  google_place: ^0.4.0
  mapbox_search: ^2.1.0+1
  http_auth: ^1.0.0
  flutter_paystack: ^1.0.5
  flutter_credit_card: ^2.0.0
  marquee: ^2.0.0
  pdf: ^3.1.0
  flutter_full_pdf_viewer: ^1.0.6
  printing: ^5.0.4
  flutter_share: ^2.0.0
  badges: ^1.2.0
  flutter_speed_dial: ^3.0.5
  url_launcher: ^6.0.3
  flat_segmented_control: ^0.1.0
  tree_view: ^0.0.5
  razorpay_flutter: ^1.2.5
  convex_bottom_bar: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  async: ^2.5.0
  flutter_slidable: ^0.6.0
  timelines: ^0.1.0
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh: ^2.0.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
     - assets/images/


  fonts:
     - family: Google-Sans
       fonts:
         - asset: assets/fonts/ProductSans-Regular.ttf
